name: C Project CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 显示目录结构（调试用）
      run: |
        echo "=== 当前目录结构 ==="
        find . -type f -name "*.c" -o -name "*.py" | sort
        echo "=== src目录内容 ==="
        ls -la src/ || echo "src目录不存在"
        echo "=== tests目录内容 ==="
        ls -la tests/ || echo "tests目录不存在"

    - name: 安装GCC编译器
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc
        gcc --version  # 验证安装

    - name: 编译C程序（带详细输出）
      run: |
        echo "开始编译C程序..."
        # 确保在正确的目录中编译
        pwd
        ls -la
        # 编译命令，显示详细输出
        gcc -o math_program main.c -v 2>&1 | tail -20
        # 检查编译结果
        if [ -f "math_program" ]; then
          echo "✅ 编译成功，生成 math_program"
          ls -la math_program
        else
          echo "❌ 编译失败，未生成 math_program"
          exit 1
        fi

    - name: 运行基础测试
      run: |
        echo "运行编译出的程序..."
        ./math_program || echo "程序运行失败"

    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: 安装测试依赖
      run: |
        cd tests
        pip install -r requirements.txt

    - name: 运行Python测试
      run: |
        # 使用更简单的测试先验证
        python tests/test_math.py -v