name: C Project CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 安装编译环境
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc

    - name: 编译C程序
      run: gcc -o math_program src/main.c

    - name: 运行基础验证
      run: |
        # 简单验证程序能运行
        ./math_program
        echo "✅ 基础验证通过"

    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: 安装测试依赖
      run: |
        cd tests
        pip install -r requirements.txt

    - name: 运行独立Python测试
      run: |
        # 运行我们写的独立测试文件
        cd tests
        python -m pytest test_math.py -v --tb=short

    - name: 生成测试报告
      run: |
        echo "=== 测试完成 ==="
        echo "所有独立测试文件已执行"
        echo "查看详细测试报告请检查上一步骤"